// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AlertDialog.tsx": () => import("../components/mockups/AlertDialog.tsx"),
  "./components/mockups/Button.tsx": () => import("../components/mockups/Button.tsx"),
  "./components/mockups/Calendar.tsx": () => import("../components/mockups/Calendar.tsx"),
  "./components/mockups/ContextMenu.tsx": () => import("../components/mockups/ContextMenu.tsx"),
  "./components/mockups/Dialog.tsx": () => import("../components/mockups/Dialog.tsx"),
  "./components/mockups/Drawer.tsx": () => import("../components/mockups/Drawer.tsx"),
  "./components/mockups/DropdownMenu.tsx": () => import("../components/mockups/DropdownMenu.tsx"),
  "./components/mockups/HoverCard.tsx": () => import("../components/mockups/HoverCard.tsx"),
  "./components/mockups/Input.tsx": () => import("../components/mockups/Input.tsx"),
  "./components/mockups/Menubar.tsx": () => import("../components/mockups/Menubar.tsx"),
  "./components/mockups/Popover.tsx": () => import("../components/mockups/Popover.tsx"),
  "./components/mockups/Select.tsx": () => import("../components/mockups/Select.tsx"),
  "./components/mockups/Sheet.tsx": () => import("../components/mockups/Sheet.tsx"),
  "./components/mockups/Spinner.tsx": () => import("../components/mockups/Spinner.tsx"),
  "./components/mockups/Toggle.tsx": () => import("../components/mockups/Toggle.tsx"),
  "./components/mockups/Tooltip.tsx": () => import("../components/mockups/Tooltip.tsx")
};
